[package]
name = "glium-probieren"
version = "0.1.0"
authors = ["Arno Haase <arno.haase@haase-consulting.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.27"
cgmath = "0.17"
